//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace iphone_Booking {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"MKQK2ZP/A:16g:银;
MKQL2ZP/A:16g:金;
MKQJ2ZP/A:16g:灰;
MKQM2ZP/A:16g:玫瑰金;
MKQP2ZP/A:64g:银;
MKQQ2ZP/A:64g:金;
MKQN2ZP/A:64g:灰;
MKQR2ZP/A:64g:玫瑰金;
MKQU2ZP/A:128g:银;
MKQV2ZP/A:128g:金;
MKQT2ZP/A:128g:灰;
MKQW2ZP/A:128g:玫瑰金;
MKU22ZP/A:16g:银;
MKU32ZP/A:16g:金;
MKU12ZP/A:16g:灰;
MKU52ZP/A:16g:玫瑰金;
MKU72ZP/A:64g:银;
MKU82ZP/A:64g:金;
MKU62ZP/A:64g:灰;
MKU92ZP/A:64g:玫瑰金;
MKUE2ZP/A:128g:银;
MKUF2ZP/A:128g:金;
MKUD2ZP/A:128g:灰;
MKUG2ZP/A:128g:玫瑰金;")]
        public string Iphone {
            get {
                return ((string)(this["Iphone"]));
            }
            set {
                this["Iphone"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("server=localhost;uid=root;pwd=123456;database=awol;Charset=utf8")]
        public string DBCon_local {
            get {
                return ((string)(this["DBCon_local"]));
            }
            set {
                this["DBCon_local"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Database=acsm_24ff61fb817a5a0;Data Source=ap-cdbr-azure-east-c.cloudapp.net;User " +
            "Id=b5fd689373a896;Password=3170f905")]
        public string DBCon_Azure {
            get {
                return ((string)(this["DBCon_Azure"]));
            }
            set {
                this["DBCon_Azure"] = value;
            }
        }
    }
}
